# Generated by Django 5.0.1 on 2024-02-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='Task_assign_data',
        ),
    ]
