# Generated by Django 5.0.1 on 2024-02-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_taskmodel_task_assign_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='Task_assign_date',
            field=models.DateField(default=None),
        ),
    ]
