# Generated by Django 5.0.1 on 2024-02-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskmodel_task_assign_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Task_assign_date',
            field=models.DateField(null=True),
        ),
    ]
