# Generated by Django 5.0.1 on 2024-02-29 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_taskmodel_task_assign_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='Task_assign_date',
        ),
    ]
