# Generated by Django 5.0.1 on 2024-03-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[('Deposite', 'Deposite'), ('Borrow', 'Borrow')], null=True),
        ),
    ]
