# Generated by Django 5.0.1 on 2024-03-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_review_name_alter_bookmodel_desc'),
        ('user', '0002_borrowhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='book.bookmodel'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='user.useraccount'),
        ),
    ]
