# Generated by Django 5.0.1 on 2024-03-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_borrowhistory_book_alter_borrowhistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowhistory',
            name='balance_after_borrow',
        ),
    ]
