# Generated by Django 5.0.1 on 2024-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
