# Generated by Django 5.0.1 on 2024-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookmodel_desc'),
        ('category', '0002_alter_categorymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
