# Generated by Django 5.0.1 on 2024-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_bookmodel_category_bookmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='desc',
            field=models.TextField(),
        ),
    ]
