# Generated by Django 5.0.1 on 2024-03-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_alter_comment_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='brand',
            new_name='car_model',
        ),
    ]
